# Generated by Django 4.1.7 on 2023-03-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='post',
            field=models.ManyToManyField(to='posts.posts'),
        ),
    ]
