# Generated by Django 4.1.7 on 2023-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_categorys_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorys',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='main_category',
        ),
        migrations.AddField(
            model_name='posts',
            name='post',
            field=models.ManyToManyField(to='posts.categorys'),
        ),
    ]
