# Generated by Django 4.1.7 on 2023-03-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_main_category_alter_posts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='posts.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='posts.category'),
        ),
    ]
