# Generated by Django 4.1.7 on 2023-04-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_text_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='realted_post',
            field=models.ManyToManyField(blank=True, related_name='realted_post', to='posts.post'),
        ),
    ]
